name: user_domain
description: User domain models, repository interfaces, and use cases.
version: 0.0.1
publish_to: 'none'
resolution: workspace

environment:
  sdk: ^3.10.8

dependencies:
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  common:
    path: ../common

dev_dependencies:
  build_runner: ^2.11.0
  freezed: ^3.2.3
  json_serializable: ^6.9.0
  flutter_lints: ^6.0.0
  test: ^1.26.3
  mocktail: ^1.0.4
