name: xogame
publish_to: "none"

environment:
  sdk: ^3.10.8

workspace:
  - apps/xoapp
  - packages/tictactoe_domain
  - packages/tictactoe_kit
  - packages/user_domain

dev_dependencies:
  melos: ^7.4.0

melos:
  scripts:
    analyze:
      run: melos exec -- dart analyze .
      description: Run static analysis in all packages

    test:
      run: melos exec --fail-fast -- "dart test"
      description: Run Dart tests in all packages (Flutter tests are separate)

    flutter_test:
      run: melos exec --fail-fast --flutter -- "flutter test"
      description: Run flutter test in flutter packages

    gen:
      run: melos exec --fail-fast -- "dart run build_runner build --delete-conflicting-outputs"
      description: Run build_runner in all packages
