name: xogame
publish_to: "none"

environment:
  sdk: ^3.10.8

workspace:
  - apps/xoapp
  - packages/common
  - packages/core
  - packages/tictactoe_domain
  - packages/tictactoe_feature
  - packages/ui_components
  - packages/user_domain
  - packages/user_feature

dev_dependencies:
  melos: ^7.4.0

melos:
  scripts:
    analyze:
      run: melos exec -- dart analyze .
      description: Run static analysis in all packages

    test:
      run: melos exec --dir-exists="test" --no-flutter -- dart test
      description: Run Dart tests in all Dart packages

    flutter_test:
      run: melos exec --dir-exists="test" --flutter -- flutter test
      description: Run Flutter tests in all Flutter packages

    gen:
      run: melos exec --fail-fast -- "dart run build_runner build --delete-conflicting-outputs"
      description: Run build_runner in all packages
