name: tictactoe_domain
description: Pure Dart package for XO Game domain logic.
publish_to: 'none'
version: 0.0.1
resolution: workspace

environment:
  sdk: ^3.10.8

dev_dependencies:
  lints: ^6.0.0
  test: ^1.26.3
