/// Tests for the [User] model factory.
///
/// Verifies that [User.create]:
/// - Creates a user with valid data
/// - Trims whitespace from name
/// - Uses provided or generates createdAt
/// - Throws [ArgumentError] for invalid names (too short/long)
///
/// Note: Basic [User] constructor is not tested as it's generated by Freezed.
library;

import 'package:test/test.dart';
import 'package:user_domain/user_domain.dart';

void main() {
  group('User.create', () {
    test('creates user with valid name', () {
      final user = User.create(
        uid: 'uid123',
        name: 'John',
        email: 'john@example.com',
      );

      expect(user.uid, equals('uid123'));
      expect(user.name, equals('John'));
      expect(user.email, equals('john@example.com'));
      expect(user.createdAt, isNotNull);
    });

    test('trims name whitespace', () {
      final user = User.create(
        uid: 'uid123',
        name: '  John  ',
        email: 'john@example.com',
      );

      expect(user.name, equals('John'));
    });

    test('uses provided createdAt', () {
      final createdAt = DateTime(2024, 1, 15);
      final user = User.create(
        uid: 'uid123',
        name: 'John',
        email: 'john@example.com',
        createdAt: createdAt,
      );

      expect(user.createdAt, equals(createdAt));
    });

    test('throws ArgumentError for invalid name', () {
      expect(
        () => User.create(uid: 'uid123', name: 'A', email: 'john@example.com'),
        throwsA(isA<ArgumentError>()),
      );

      final longName = 'a' * (User.maxNameLength + 1);
      expect(
        () => User.create(uid: 'uid123', name: longName, email: 'john@example.com'),
        throwsA(isA<ArgumentError>()),
      );
    });
  });
}
