name: user_feature
description: User authentication and profile feature with Firebase.
version: 0.0.1
publish_to: 'none'
resolution: workspace

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.4.0
  firebase_auth: ^6.1.4
  cloud_firestore: ^6.1.2
  hooks_riverpod: ^3.1.0
  riverpod_annotation: ^4.0.0
  freezed_annotation: ^3.1.0
  user_domain:
    path: ../user_domain
  core:
    path: ../core

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.11.0
  freezed: ^3.2.3
  riverpod_generator: ^4.0.0+1
